-- CreateEnum
CREATE TYPE "VideoFailureReason" AS ENUM ('INPUT_TOO_LARGE', 'DURATION_EXCEEDED', 'UNSUPPORTED_CONTAINER', 'UNSUPPORTED_VIDEO_CODEC', 'UNSUPPORTED_AUDIO_CODEC', 'CORRUPT_OR_UNREADABLE', 'TRANSCODE_FAILED');

-- AlterTable
ALTER TABLE "Video" ADD COLUMN     "failureReason" "VideoFailureReason",
ADD COLUMN     "posterKey" TEXT;
